import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { OnboardingAnswers } from "@mstrmnd/onboarding-agent";
import { computeSeal } from "./seal.js";

export { computeSeal, verifySeal } from "./seal.js";

export interface GeneratedContext {
  contextPath: string;
  trackedFiles: string[];
  seal: string;
  version: number;
}

const CONTEXT_VERSION = 1;

/**
 * Tracked file paths relative to contextPath.
 * The seal covers all of these.
 */
const TRACKED_FILES = [
  "identity.md",
  "config.json",
  "agents/roles.json",
  "connectors/filesystem.config.json",
];

/**
 * Generate the locked context folder structure from onboarding answers.
 * Creates all required files and writes the .mstrmnd-seal integrity checksum.
 */
export function generateContext(answers: OnboardingAnswers, contextPath: string): GeneratedContext {
  mkdirSync(join(contextPath, "agents"), { recursive: true });
  mkdirSync(join(contextPath, "connectors"), { recursive: true });

  writeIdentity(contextPath, answers);
  writeConfig(contextPath, answers);
  writeAgentRoles(contextPath, answers);
  writeConnectorConfig(contextPath, answers);

  const seal = computeSeal(contextPath, TRACKED_FILES);
  writeFileSync(join(contextPath, ".mstrmnd-seal"), seal, "utf-8");

  return {
    contextPath,
    trackedFiles: TRACKED_FILES,
    seal,
    version: CONTEXT_VERSION,
  };
}

function writeIdentity(contextPath: string, answers: OnboardingAnswers): void {
  const now = new Date().toISOString();
  const roles = answers.customAgentRoles.length
    ? answers.customAgentRoles.map((r) => `- ${r}`).join("\n")
    : "- default";

  const integrations = answers.integrationEndpoints?.length
    ? answers.integrationEndpoints
        .map((e) => `- **${e.name}**${e.url ? `: ${e.url}` : ""}`)
        .join("\n")
    : "- none";

  const content = `# MSTRMND Identity — ${answers.companyName}

> Auto-generated by MSTRMND context-generator. Do not edit manually.

## Organization
- **Name**: ${answers.companyName}
- **Domain**: ${answers.domain}
- **Contact**: ${answers.contactEmail ?? "not specified"}

## Vault
- **Path**: ${answers.vaultPath}

## Model Configuration
- **Provider**: ${answers.modelPreference}
- **Model**: ${answers.modelId}

## Agent Roles
${roles}

## Integrations
${integrations}

## Metadata
- **Generated**: ${now}
- **Version**: ${CONTEXT_VERSION}
`;
  writeFileSync(join(contextPath, "identity.md"), content, "utf-8");
}

function writeConfig(contextPath: string, answers: OnboardingAnswers): void {
  const config = {
    version: CONTEXT_VERSION,
    generatedAt: new Date().toISOString(),
    organization: {
      name: answers.companyName,
      domain: answers.domain,
      contactEmail: answers.contactEmail ?? null,
    },
    vault: {
      path: answers.vaultPath,
    },
    model: {
      provider: answers.modelPreference,
      modelId: answers.modelId,
    },
    agents: {
      roles: answers.customAgentRoles,
    },
    integrations: answers.integrationEndpoints ?? [],
  };
  writeFileSync(join(contextPath, "config.json"), JSON.stringify(config, null, 2), "utf-8");
}

function writeAgentRoles(contextPath: string, answers: OnboardingAnswers): void {
  const roles = answers.customAgentRoles.map((role) => ({
    id: role.toLowerCase().replace(/\s+/g, "-"),
    name: role,
    description: `Custom agent role: ${role}`,
    capabilities: [],
  }));
  writeFileSync(
    join(contextPath, "agents", "roles.json"),
    JSON.stringify({ roles }, null, 2),
    "utf-8"
  );
}

function writeConnectorConfig(contextPath: string, answers: OnboardingAnswers): void {
  const config = {
    filesystem: {
      vaultPath: answers.vaultPath,
      watchEnabled: false,
      includeExtensions: [".md", ".txt", ".json"],
    },
  };
  writeFileSync(
    join(contextPath, "connectors", "filesystem.config.json"),
    JSON.stringify(config, null, 2),
    "utf-8"
  );
}
